[book]
language = "en"
src = "src"
title = "PicoMite User Manual"
authors = ["Geoff Graham", "Peter Mather"]
git-repository-url = "https://github.com/Yamavu/PicoMite_User_Manual"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
copy-fonts = true
